-- D1 fixtures switch from TheSportsDB (API, quota-limited shared free key)
-- to footmercato.net scraping (see api/sync-d1.ts, api/live-scores.ts),
-- matching the pattern already used for cup_fixtures/european_fixtures.
--
-- `id` stays a small stable surrogate key rather than footmercato's own
-- match id (a ~19-digit number that would need `bigint` and reintroduce the
-- PostgREST/JS bigint-precision bug already worked around for
-- cup_fixtures/european_fixtures via match_url) — every existing reader of
-- `Fixture.id` in the app assumes a plain safe-integer number, so leaving
-- its type/meaning alone avoids touching any of that code. New rows just
-- don't specify `id`; Postgres assigns the next one. The sequence is
-- restarted well above every historical TheSportsDB id (max was 2,496,995
-- as of 2026-08-08) so old and new rows never collide.
alter table fixtures add column if not exists match_url text;
create unique index if not exists fixtures_match_url_idx on fixtures (match_url);

alter table fixtures alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('fixtures', 'id'), 10000000, false);
